### ISSUE TITLE
Creation of Dictionaries

### ISSUE THREAD

**Issue by LuRsT** [gkbrk/minelib#3]
Since you're creating a lot of dictionaries, how about using this method instead of the one you're using?

```
 def parse_player_list_item(fileobj, socket):
-    result = {}
-    result["PlayerName"] = mc_datatype.readString(fileobj)
-    result["Online"] = mc_datatype.readBoolean(fileobj)
-    result["Ping"] = data_type_parser.parse_short(fileobj)
+    result = {
+        'PlayerName': mc_datatype.readString(fileobj),
+        'Online': mc_datatype.readBoolean(fileobj),
+        'Ping': data_type_parser.parse_short(fileobj),
+    }
     return result
```

**Comment by gkbrk** [comment]
I think assigning them to variables is better because sometimes you need to use them to get more data. For example at 0X1D Destroy Entity, I need the entity count to loop the entity ID's so I can't just return them. But I can put them to normal variables and return it like;

``` python
 def parse_player_list_item(fileobj, socket):
-    result = {}
-    result["PlayerName"] = mc_datatype.readString(fileobj)
-    result["Online"] = mc_datatype.readBoolean(fileobj)
-    result["Ping"] = data_type_parser.parse_short(fileobj)
+    playername = mc_datatype.readString(fileobj)
+    online = mc_datatype.readBoolean(fileobj)
+    ping = mc_datatype.readShort(fileobj)
+    return {"PlayerName":playername, "Online":online, "Ping":ping}
```

I also made an addition to the code, making it return the packet name (for example "Player_List_Item") with the results.

**Comment by LuRsT** [comment]
Yes, if you intend on making changes to those values, your solution is better :+1:
